[package]
name = "guessing_game_numbers"
version = "0.1.0"
authors = ["joshua <blitzmasterj24@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
